### ISSUE TITLE
double script run

### ISSUE THREAD

**Issue by gullerya** [guybedford/es-module-shims#126]
It is probably more of a question than an issue, to understand it first.

When the polyfill is used (FF, Safari) it causes the scripts to run twice, once on their own and second time when the shim reapplying them with the maps effective.
First - am I getting it right?
Second - it also looks like not only those scripts that are doing the bare imports are being re-executed, but also their  whole upstream, which is also sounds logically right, again, just to be sure I'm getting it right.

Last - what would you suggest to do in order to have some scripts out of this cycle?
I have some main entry point dealing with the document state and running it twice causes undesired effect on the app.

Thanks in advance and kudos for the cool lib!

**Comment by guybedford** [comment]
@gullerya the polyfill will basically run through the modules that are supposed to execute and try to work out if they would have executed correctly or not based on checking their features against feature detections. If a module is using a feature not supported (usually bare specifiers) the polyfill will then reexecute the entire tree using its own execution process. Because all modules have to be resolved before any will execute, in most cases there should not be double execution.

There are quite a few edges to this feature detection though so if you have a case that seems like it should not be double executing please do share the exact scenario and I can tell you if it's a bug or not.

**Comment by guybedford** [comment]
There was a polyfill mode bug fixed in #130 and released in 0.10.6. Perhaps try that out and see if that resolves the issue here.

**Comment by gullerya** [comment]
Oh my, sorry for non-reacting on the previous one.

I'd first state the cases (which I've actually solved in the consumer land and without compromising correctness, so win-win from my POV), then you'll probably see if it any relevant.

> somewhat meta code examples below, using bad practice of global state to exemplify the thing

2 cases on my table:
- dynamic import in the mid of the script case:
  ```js
  globalThis.a = window.a ? window.a + 1 : 1;

  const bareImport = import('bare-spec');
  ```
  in the case above we'll end up with `window.a === 2`, since we'll have the root scope executed once until the bare import fails and then re-applied by the polyfill, right?
- cascade effect:
  ```js
  // root module
  import './regular-specifier-a.js`;
  import './regular-specifier-b.js`;
  ```
  those will be executed at least at race (and probably in some envs sequentially), which means that:
    - if the `regular-specifier-b.js` has within it bare import
    - and if the `regular-specifier-a.js` has global state mutation as in the first bullet
    - and if the polyfill applied
    - then both - `root` module and `regular-specifier-a` will re-run

Are those assumptions correct?
If yes - I'm not sure #130 or any other fix can help here (unless the scripts execution is fully intercepted and none of them executed until fully parsed and patched by the polyfill), and this is just fine, see below.

Anyway, seems like some relatives simple circuit-breaking can be applied so, that the bare importers will NOT be part of a state mutating chain (at least in my case that was quite a correct split to do).

**Comment by guybedford** [comment]
> dynamic import in the mid of the script case:

Yes that's correct, the polyfill will double execute the parent module of the dynamic import because it doesn't know if there are conditions being applied to the dynamic import execution.

> cascade effect

Bare imports in the static graph will throw the entire graph and not execute any modules at all. So this case will have no double execution. The only possibility of double execution here is if you have two import maps, one import map using a `src=""` and the other as inline, with both providing resolutions for the same bare specifier. In that case the polyfill will double execute currently, although this logic could be rethought.

**Comment by gullerya** [comment]
To make sure we are on the same page with regard to the last point:
- it is clear that the whole static tree will throw, so within that tree no side effect 'pollution' expected
- but sibling trees (like in the example I gave) MAY cause that double execution (unless the whole static import tree is fully parsed and verified to the last of the leaves BEFORE the actual execution happens, I don't think this is the `import` algo though)

**Comment by guybedford** [comment]
@gullerya the root module is the root of the static tree, there is no concept of sibling trees unless you are referring to separate dynamic `import()` calls or top-level `<script type="module">` calls.

**Comment by gullerya** [comment]
Having:
```
import './a.js';
import './b.js';
```
in the root module, can't you say that `a` and `b` are sibling subgraphs? For instance if they are both imported in parallel?

**Comment by guybedford** [comment]
@gullerya no that is one graph: `root -> a, root -> b` where all modules are resolved ahead of time before any execution.

**Comment by gullerya** [comment]
Okay, got it, that was a lacunae in my knowledge.
Thanks for the clarification, first.
I think that this ticket may be closed then, since:
- double execution may happen
- for the legitimate double execution (dynamic import, mixed import maps) - the solution should be done in the consumer land
- beside that there should be no issues
