### ISSUE TITLE
Improving CSP policy requirements

### ISSUE THREAD

**Issue by guybedford** [guybedford/es-module-shims#167]
In theory we can get to just CSP blob with:
* Updating the lexer to not use eval but use readString from acorn
* Updating all usage of eval to use dynamic import instead
* Updating all feature detections to not use eval or an iframe

Seems worthwhile. Not on my list though.

**Comment by Lcfvs** [comment]
The PoC: https://codesandbox.io/s/epic-murdock-l1nko (the implementation is into the `src`)

 * It replaces the need of `eval()` by the dynamic import into the shim
 * It provides the dynamic import to the lexer parse to avoid `eval()` if possible
 * It attempts to add an **empty** importmap to the documents to detect its native support (it just fails if supported, then we know we can skip any other process

But the tests can't run, since `importShim()` is now declared asynchronously in my version.
