### ISSUE TITLE
Incomplete dynamic import support

### ISSUE THREAD

**Issue by Lcfvs** [guybedford/es-module-shims#168]
Actually, a dynamic import fails if it calls a module importing a dependency declared into the importmap... just like if there is no importmap.

A potential solution is maybe to replace the dynamic `import()` by the `importShim()`, at the same time as you replace the dependencies, using the lexer.

To reproduce it, with this importmap
```json
{
  "imports": {
    "anticore": "https://ga.jspm.io/npm:anticore@4.6.3/index.js"
  }
}
``` 
`main.js` 
```js
import('./test.js')
``` 
`test.js` 
```js
import 'anticore'
```

**Comment by guybedford** [comment]
I was able to verify this is indeed a bug, thank you for posting I'll aim to have a fix up soon.

**Comment by guybedford** [comment]
So after checking this carefully it's actually not a bug.

These are just edge cases of the polyfill mode detection as described in the readme for dynamic imports, and also why in polyfill mode it is recommended to use patterns that fail early.

Dynamic import is the big issue for polyfill mode detection, because of the fact that the code will work natively, but fail the dynamic import promise, therefore polyfilling a script that uses dynamic import only runs the risk of executing that top-level module script twice. Which is not ideal at all.

For this reason, I think we should just retain the simple polyfill contract that the polyfill will only polyfill graphs that will definitely fail the native loader statically, and does not do deep dynamic import tracing. That's a pretty clear requirement I think.

**Comment by Lcfvs** [comment]
Ok, probably better to still rely on a bundle as fallback, in that case
