### ISSUE TITLE
Infinite loop on Firefox 60

### ISSUE THREAD

**Issue by Lcfvs** [guybedford/es-module-shims#169]
The problematic importmap
```json
{
  "imports": {
    "anticore": "https://ga.jspm.io/npm:anticore@4.6.3/index.js"
  }
}
```
(But it works natively on Chrome and with the shim on Firefox 67+)

**Comment by guybedford** [comment]
I just tried this out with the following HTML from JSPM Generator - https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hSAQykvOLUh1M9Mz0jAHw7bXYHQA.

When I run that on Firefox and in Chrome it works fine for both.

Let me know if you are still having the issue, otherwise it would help if you could post the exact steps for the replication.

**Comment by Lcfvs** [comment]
> When I run that on Firefox and in Chrome it works fine for both.

On Firefox 60?

I just tested it again, with the same code: https://codesandbox.io/s/nostalgic-shadow-mmj7j?file=/index.html

**Comment by guybedford** [comment]
Ahh thank you for sharing the replication I was finally able to see the case and post a fix in https://github.com/guybedford/es-module-shims/pull/176.
