### ISSUE TITLE
importmap in Workers

### ISSUE THREAD

**Issue by trusktr** [guybedford/es-module-shims#206]
The README seems to indicate that it won't work in any browser other than Chrome. 

Is it possible to run an entry point entirely through the polyfill, for example, so that it can run in all browsers (in a Worker)? I'm hoping maybe we can do something like follows in worker code:

```js
addImportMap(`
  {
    "imports": {
      ...
    }
  }
`)

importShim('./path/to/worker-module.js')
```

whereby it will completely bypass any native ES Module APIs as needed. Is that currently possible? It is not clear from the docs.

**Comment by guybedford** [comment]
> The README seems to indicate that it won't work in any browser other than Chrome.

Can you clarify what specifically you're referring to? Worker support you mean?

There was a previous version of the package that included web worker support via https://github.com/guybedford/es-module-shims/pull/17 for import maps for Chrome only, since only Chrome supports dynamic import in workers. This was reverted due to a lack of browser support but will be added back as soon as we are able to support it across all browsers again.

**Comment by trusktr** [comment]
Yeah, I was wondering about worker support. Importmap in workers wasn't working in all browsers.

**Comment by guybedford** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1247687 is the issue we need to land in Firefox before we can support this.

**Comment by marcofugaro** [comment]
> There was a previous version of the package that included web worker support via #17 for import maps for Chrome only, since only Chrome supports dynamic import in workers. This was reverted due to a lack of browser support but will be added back as soon as we are able to support it across all browsers again.

hello @guybedford any way we can use the import maps polyfill (or shim) in web workers now?

**Comment by guybedford** [comment]
@marcofugaro I haven't checked recently if dynamic `import()` is available yet in Firefox web workers. That is the key primitive that is needed to reinstate #17 with Firefox support. There has been some progress in Firefox recently so it could be worth verifying!

**Comment by guybedford** [comment]
@costingeana nice to hear the approach is still working well for you there! If the checks are relatively minimal I would be more than happy to take such a PR, and agreed it might be simpler to just require custom wrapping work in the workflow. Documenting such a worker workflow would be a really nice addition for these browsers certainly. Just let me know if there's anything more you need from me to get going on that.

**Comment by costingeana** [comment]
@guybedford , I just added a pull request. Please let me know what can I do better. Thank you.

**Comment by guybedford** [comment]
Landed in https://github.com/guybedford/es-module-shims/pull/300, thank you @costingeana!

**Comment by costingeana** [comment]
You're welcome, @guybedford. Thank you too.

**Comment by bman654** [comment]
I'm a bit confused about this feature.  Doesn't this end up loading the worker code in _classic_ mode (since you do not include the `{type: "module" }` option in the Worker constructor?  Does `importShim` somehow convert the module syntax to classic syntax for you?.


Well, I just tried it and it indeed works.
Here is [a working example](https://jspm.org/sandbox#H4sIAAAAAAAAA+1WbW/bNhD+7l9x1QpEQmKpCZa2c6wgfQnaBvVa1M1eMAw1LZ0jJhIpkFQcx/B/35GUnNhYigzoxxlIJPLunjs+9yIOn+QyM4saoTBVedwbdg9k+XEPYFihYZAVTGk0adCYWf9l4ASGmxKPz4V75sPEr9cmglWYBtcc57VUJoBMCoOCIOY8N0Wa4zXPsO8We8AFN5yVfZ2xEtN9cjBMfATDqcwXDvVJv08PgLPx5xG8Q4GKGangQ2XxYcRqJz3NuYHzLx8HdB5T60GSXHSq8aWuq5jL5Kfzg98u/3z3+urt6JlajG/Pxuf7xWJUfh6Pbz9lb99+Gd1+/WN0++H01XsxUy91/uoVYff7LgydKV4bsJSlAXfOK1Y7SpYugnZTB4N2g7ZKmTNd0E6wjoqtwxF1NfAKJz/H+y/ig/3EL0kj2Osg1M2l/g6AFZ+8iA/jF0nOtUlQVwkXOd5YEIex8lCBzmSNG9H9C+Q9MSkYXfLpd5w7+clBTOEn7j1G/XztmFz3uv/2b5h4Di1lbWLhdAwjmTclwrjglR50aSVqNdSyXMx4WcKM8l05NQ1TJecalYY5N4VsDPB7Frqp3SJkZIU3GVLG3hRKVggvf9mNtnKZ4wwVaJWlDx0Qdd/77Wsb3sl+/Dw+6IjeENlTQ6ak1lLxCy7SgAkpFpVsdHC8ffKSiytQWKaBh6jpXbI8gELh7MFgHqyVpMPdqFEPHbQysI2oDcylukL1RuYIKUx6vZa9JXHBmtIA0/BtBTOibF29R2slu90JXV0e9a6ZAq7HRvHMEGI4a0RmuBRhBEs6ommUgCem4PoIVlEYHfVqqc0ItWYXGAY+Gmjj5pTADiiA3TVu1POxM7UgybdYMUHGz/bgMNqAOxt/+jW2COKCzxYhqUdRz0brXmPdTK2jKYYK0mP4jqWKyHDS22bsXJXkn4ZMnClkBj9NLzEztA4FzuF1KafhX3faf+/B0mZiADusrkueMctLcsmumT/vzoq8tE5sDd25+AHlOGe6cp3YS5K2RWyHxRdofIvR4KQc+QxpYAKwqs2iVSVhDPCBqkE31Ds2fzY7U8xYoxFo1BZUKELaZw6GWx0JtZIZEWo9mgKBPjBkLAwh3QUAAjHXVhtvKAMIzJpVXDuEEg00Gq6EnMO8QAFzhIxis04t5F109GupW+8Rcf9P4kdMYkubLDEu5UV4r+6iDcFWR6xJppL9zy1/H3dyz/LpslusJutO8A00dh3ymIab/KARZGuzQ0k3p09bvS4kHe48Xd5jbbUTdfPR9RfL87v+erp8kMbVhpkF3ZgzBBvTwMiKEO2sojvYV2oy+tyFdCraWFI70IcQ0J6JoCaPnDabudCGKUOhtaRPfG5zzK055r97alKwbPtFuJUe8movfFSY1cKLArBH28KwtJxe0yz4SJ1h72VhgEpJFeyBP08XltsNA9vrbWJyjnnQVl0mG2FT/OwR+JVPMHlY1wNem8g1lR0zCrX93qVAu3HODDvqAWyw0yL4752PZkA16w1txdJcm0HogtrdhTSlwCw+jT/6bUe4UXRbZdEOG/9d2987jKIgOnK9arncuDoNE38xpnuyu7D/A4dDOkLICwAA).
