### ISSUE TITLE
Clarification on use of modulepreload

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-shims#259]
I'm seeing double network fetch when using `modulepreload` in shim mode:

```
<html>
  <head>
    <script async src="https://ga.jspm.io/npm:es-module-shims@1.4.4/dist/es-module-shims.js"></script>
    <link rel="modulepreload" href="/test.js" />
  </head>
  <body>
    <script type="module-shim">
      import test from "/test.js";
      console.log(test);
    </script>
  </body>
</html>
```

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/11994993/153650467-5d77a4ad-03e0-4bf8-a192-f7ceff74ff9d.png">

Browsing around the issues I see this was already discussed before, but I wasn't sure about the conclusion. I see there is a `modulepreload-shim` option, but it's only listed under the integrity docs: https://github.com/guybedford/es-module-shims#enforce-integrity should we use that to preload modules? It delays the preloads until es-module-shims itself is loaded.

**Comment by guybedford** [comment]
@LarsDenBakker when using shim mode, `modulepreload-shim` should always be used instead of `modulepreload` because preloading the fetch cache is a completely separate thing to preloading the module cache and some browsers like Safari do not share these caches at all.

Perhaps we can clarify this in the documentation?

**Comment by LarsDenBakker** [comment]
@guybedford thanks for confirming. indeed it would be good to point this out in the docs

**Comment by guybedford** [comment]
Thanks for the follow-up!
