### ISSUE TITLE
Enhancement suggestion: Provide cyclical live bindings support

### ISSUE THREAD

**Issue by badde-media** [guybedford/es-module-shims#271]
Since the polyfill doesn't provide live bindings support, problems with cycles in your code may occur. The workaround you've shown in [issue 270](https://github.com/guybedford/es-module-shims/issues/270) could easily be automated, so that less experienced devs wouldn't run into such problems, no?

**Comment by guybedford** [comment]
Note this is specifically live bindings support for cycle shell modules - live bindings are fully supported otherwise.

Unfortunately there is no easy way to make this work, this is explicitly listed in the readme as a special case of the polyfill technique.

The best we could likely do is try to detect errors in cycle modules and add additional context for the error message.

**Comment by guybedford** [comment]
Closing as a cantfix / wontfix.

**Comment by guybedford** [comment]
Note, I finally came up with an approach that can possibly finally solve this issue in https://github.com/guybedford/es-module-shims/pull/296 but it still would require some more work to be a proper fix.
