### ISSUE TITLE
Issue with dynamic imports since v.1.5.3

### ISSUE THREAD

**Issue by paulinemss** [guybedford/es-module-shims#283]
Hi there! 

First, thanks a lot for this. I've been looking into implementing import maps in our application and this was exactly what I was looking for to ensure browser compatibility! 

However, since v.1.5.3 I'm having issues with dynamic imports. Find below a simple case with 2 files: `index.html` and `module.js`. 

The dynamic import below does not work in Firefox (version `99.0`). 
_It does_ work if I use v.1.5.2 or below. 

`index.html`
```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hello World</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script async src="https://ga.jspm.io/npm:es-module-shims@1.5.4/dist/es-module-shims.js"></script>

    <script type="importmap">
    {
      	"imports": {
    		"module": "./module.js"
	    }
    }
    </script>
    <script type="module">
      // does not work since v.1.5.3
      import('module').then(mod => mod.default());
     
     // still works
     import mod from 'module';
     mod();
    </script>
  </head>
  <body>
  </body>
</html>
```

`module.js`
```javascript
export default function module() {
    console.log('module has loaded');
}
```

**Comment by chase-moskal** [comment]
i confirm -- i found the same issue in the recent version, reverted back to 1.52 in the meantime

**Comment by guybedford** [comment]
This is unfortunate in that it was a bug that this worked before.

The reason is that `<script type="module">import('x')</script>` is not a static error - it will execute in Firefox. So the polyfill mode should not be polyfilling the above case. This is because otherwise the polyfill risks double execution for example if you had:

```html
<script type="module">
doThingThatMustOnlyHappenOnce();
if (false) import('app');
</script>
```

we shouldn't rerun that again in the polyfill as it would break things and risk double DOM attachments and things like that.

Instead you should either use:

```html
<script type="module">import 'bare-specifier'</script>
```

which is a clear static error. Or instead use the dynamic import polyfill wrapper directly:

```html
<script type="module">importShim('app')</script>
```

There is some more info on this in this section of the readme - https://github.com/guybedford/es-module-shims#polyfill-edge-case-dynamic-import.

If you're interested in even more background this section of a blog post I wrote recently covers it as well - https://guybedford.com/es-module-shims-production-import-maps#polyfill-mode.
