### ISSUE TITLE
Safari 16.2: Syntax error, `Unexpected token '}'`

### ISSUE THREAD

**Issue by fabacab** [guybedford/es-module-shims#343]
When using version 1.6.2 of `es-module-shims` in Safari 16.2, in this fashion:

```html
<script async src="https://cdn.jsdelivr.net/npm/es-module-shims@1.6.2/dist/es-module-shims.min.js"></script>
<script type="importmap">
{
    "imports": {
        "@fullcalendar/core": "https://cdn.skypack.dev/@fullcalendar/core@6.0.1?min",
        "@fullcalendar/daygrid": "https://cdn.skypack.dev/@fullcalendar/daygrid@6.0.1?min",
        "@fullcalendar/timegrid": "https://cdn.skypack.dev/@fullcalendar/timegrid@6.0.1?min",
        "@fullcalendar/list": "https://cdn.skypack.dev/@fullcalendar/list@6.0.1?min",
        "@fullcalendar/icalendar": "https://cdn.skypack.dev/@fullcalendar/icalendar@6.0.1?min",
        "@fullcalendar/rrule": "https://cdn.skypack.dev/@fullcalendar/rrule@6.0.1?min"
    }
}
</script>
```

I see the error `SyntaxError: Unexpected token '}'` in the Safari developer console:

<img width="675" alt="Screen Shot 2022-12-27 at Dec 27, 3 23 55 PM" src="https://user-images.githubusercontent.com/18677/209718874-28fd52e2-064d-44ae-bb2d-0e6e7be7b920.png">

Only Safari is experiencing this problem; for example, Firefox 108 is behaving wonderfully.

I'd be super appreciative of any advice you can offer, and of course if you need more information please let me know what would be helpful and I'll try to provide you with it. 🙏 Thanks!

**Comment by guybedford** [comment]
Safari unfortunately doesn't use source URLs to report the correct module the error is coming from, so instead ES module shims appears as the culprit in the stack trace on first look.

The ed937be8-b500-... URL that causes the error is the actual module file itself that is causing the issue, likely due to a syntax error that is a Safari specific JS difference (perhaps something like class fields or some browser feature like that), it should still be clickable to inspect that source hash and see the underlying source though.

**Comment by fabacab** [comment]
Hmm, I apologize for my ignorance in this area, though it looks like the code that's causing a file was rewritten (maybe by `es-module-shims`?) since it no longer appears as the original does. Here's a screenshot, followed by a comparison.

When clicking through to the line that generates a syntax error, I see this:

<img width="1260" alt="Screen Shot 2022-12-29 at Dec 29, 1 54 31 PM" src="https://user-images.githubusercontent.com/18677/209996646-0ee8aca0-73be-4cd1-a1c4-10bf7f3bf54d.png">

As you can see, there's this line here that begins with a semicolon. In the original file, the code is simply:

```js
// Import our own module code sources.
import mapPlugin from './custom-views/map.js';
import EventSources from './event-sources.js';
import FullCalendarEvent from './event.js';

export const corsbase = 'https://cors.anarchism.nyc';
export const domparser = new DOMParser();
```

I'm not sure what about this code would cause the syntax error in Safari. Do you have any more thoughts?

**Comment by guybedford** [comment]
Yes the module rewrapping is how es module shims works.

In your case the syntax error shown in the screenshot is that a ‘catch’
handler requires a parameter in Safari (optional catch bindings we’re a
later JS feature).

So it must be “catch (_e) {“. Happy to help!

**Comment by fabacab** [comment]
Okay, thanks for that hint! However, my confusion stems from the fact that in the original source code there are no `try…catch` blocks at all. Given that, what should I change to fix the syntax error given that it is not the original code in which the syntax error exists?

**Comment by guybedford** [comment]
@fabacab yes this is a bug in the cycle handling of es-module-shims - the `default: new` is invalid syntax since `new` is a reserved word. That a `default` export was picked up is incorrect based on your code example, but I'm just trying to track down why it picked up this default export to begin with.

Do you have a complete replication you can share? This named exports list comes directly from the es-module-lexer analysis but just lexing the source code example you provided isn't enough for me to isolate the case.

**Comment by guybedford** [comment]
A bug along these lines was actually just fixed in es-module-lexer's last release, so I've just pushed a 1.6.3 of es-module-shims with this upgrade, if you can try that - that new version may well resolve the issue as well. If not, a replication would help a lot further.

**Comment by guybedford** [comment]
es-module-shims@1.7.0 fixes some default export cases, I believe this bug should have been caught by that if we had a replication. Unfortunately we only have a derogatory commit reference to go by.
