### ISSUE TITLE
support for `document.write` importmaps

### ISSUE THREAD

**Issue by trusktr** [guybedford/es-module-shims#351]
`<script type=importmap src="foo.json">` is not supported yet in browsers, so what I do in Chrome is this:

```html
<script src="/importmap.js"></script>
<!-- or -->
<script src="/importmap.js" map="path/to/map.json"></script>
```

to avoid manually embedding a map, where `importmap.js` has

```js
{
	function loadImportmap() {
		const src = document.currentScript.getAttribute('src')
		const srcUrl = resolveUrl(src)
		const srcFolderParts = srcUrl.split('/')
		srcFolderParts.pop()
		const srcFolder = srcFolderParts.join('/')
		const map = document.currentScript.getAttribute('map') || srcFolder + '/importmap.html'

		const r = new XMLHttpRequest()
		r.open('GET', map, /*synchronous!*/ false)
		r.send()
		document.write(r.responseText)
	}

	let a

	function resolveUrl(string) {
		if (!a) a = document.createElement('a')
		a.href = string
		return a.href
	}

	loadImportmap()
}
```

and `importmap.html` has something like

```html
<script type="importmap">
	{
		"imports": {
			"whatever": "path/to/whatever.js"
		}
	}
</script>
```

This works nicely with native importmaps, but the polyfill doesn't work in this case.

**Comment by guybedford** [comment]
If you do the above, then dynamically load es-module-shims into the page, that should work fine here. Did you try that?

**Comment by trusktr** [comment]
Not sure what you mean, can you explain? I do see this,

https://github.com/guybedford/es-module-shims#dynamic-import-maps

but was hoping to avoid using `-shim` postifxes.

**Comment by guybedford** [comment]
@trusktr es-module-shims will handle the following cases:

1. When it is loaded, it will read the DOM and apply the polyfill to all script tags in the page. If it is loaded before DOMContentLoaded it will also add a DOMContentLoaded to apply the polyfill at that point.
2. It will also attach DOM mutators to then polyfill any dynamic script tag injections as well.

It cannot detect `document.write`, so if you rather load es-module-shims after your `document.write` that should work instead.

Specifically, it would help if you could post a bug if the above isn't working as expected, but the use case is entirely provided for by the project, so I'm not sure what the issue is.

**Comment by guybedford** [comment]
@trusktr es-module-shims will handle the following cases:

1. When it is loaded, it will read the DOM and apply the polyfill to all script tags in the page. If it is loaded before DOMContentLoaded it will also add a DOMContentLoaded to apply the polyfill at that point.
2. It will also attach DOM mutators to then polyfill any dynamic script tag injections as well.

It cannot detect `document.write`, so if you rather load es-module-shims after your `document.write` that should work instead.

Specifically, it would help if you could post a bug if the above isn't working as expected, but the use case is entirely provided for by the project, so I'm not sure what the issue is.

**Comment by trusktr** [comment]
Thanks! That worked! I just had to change

```html
<script async ...
```

to

```html
<script defer ...
```
