### ISSUE TITLE
Shims broken if specifier is a relative path

### ISSUE THREAD

**Issue by nieyuyao** [guybedford/es-module-shims#417]
When I run the following HTML on Safari(15.4), the shims don't work as expected(it doesn't print out the `jQuery` constructor).

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script
      async
      src="https://unpkg.com/es-module-shims@1.9.0/dist/es-module-shims.js"
    ></script>
    <script type="importmap">
      {
        "imports": {
          "./jquery.js": "https://unpkg.com/jquery@3.7.1/dist/jquery.js"
        }
      }
    </script>
    <script type="module">
      import "./jquery.js";
      console.log($);
    </script>
  </head>
  <body></body>
</html>
```

Shims work correctly  if I change the specifier to `jquery.js`.
```html
...
 <script type="importmap">
      {
        "imports": {
          "jquery.js": "https://unpkg.com/jquery@3.7.1/dist/jquery.js"
        }
      }
 </script>
 <script type="module">
      import "jquery.js";
      console.log($);
</script>
```

Shims still doesn't work if change  specifier to `/jquery` (as #390 pointed out).
```html
<script type="importmap">
      {
        "imports": {
          "/jquery": "https://unpkg.com/jquery@3.7.1/dist/jquery.js"
        }
      }
    </script>
    <script type="module">
      import "/jquery";
      console.log($);
    </script>
```

 I debugged code and found `./jquery.js` is considered "non bare specifier". So the `<script type="module">` doesn't need shims.

```js
async function _resolve (id, parentUrl) {
  const urlResolved = resolveIfNotPlainOrUrl(id, parentUrl) || asURL(id);
  return {
    r: resolveImportMap(importMap, urlResolved || id, parentUrl) || throwUnresolved(id, parentUrl),
    // b = bare specifier
    b: !urlResolved && !asURL(id)
  };
}
```

How should I use relative path specifiers?

**Comment by guybedford** [comment]
As described in the readme at https://github.com/guybedford/es-module-shims?tab=readme-ov-file#polyfill-explainer, you must use a bare specifier to cause the module load to fail in modules browsers without import maps support, and only then will the polyfill kick in.

Any syntax failure at any point in the graph will suffice for es-module-shims to see that there is a failure it can correct. But otherwise, without such a failure, we risk executing the same modules twice which could break apps.

You can use relative path specifiers, just make sure you are using a breaking bare specifier or other modern syntax feature somewhere in the graph so that it will definitely fail in browsers without import maps support, so there is no double execution risk.
