### ISSUE TITLE
ObjectURL should to be revoked?

### ISSUE THREAD

**Issue by zaygraveyard** [guybedford/es-module-shims#58]
This library creates multiple ObjectURLs and never revokes them.
And, as stated on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL#Memory_management), they should be revoked:

> Each time you call `createObjectURL()`, a new object URL is created, even if you've already created one for the same object. Each of these must be released by calling `URL.revokeObjectURL()` when you no longer need them.
>
> Browsers will release object URLs automatically when the document is unloaded; however, for optimal performance and memory usage, if there are safe times when you can explicitly unload them, you should do so.

**Comment by guybedford** [comment]
Typically an application would be loading at most a few MiB of JavaScript. There is a natural upper bound here is the module registry is not an operation that grows linearly over time like many other operations. Rather the module registry grows more like a reverse exponential or log.

Because footprint of the library is the most important to loading, it was deemed unnecessary to incure the upfront network bytes for a few MiB memory savings (likely only a percent of what is used by the app anyway).

**Comment by zaygraveyard** [comment]
Thank you for the clarification :+1:
