### ISSUE TITLE
Service worker fetch for import maps

### ISSUE THREAD

**Issue by lastmjs** [guybedford/es-module-shims#72]
It looks like the import maps polyfill doesn't work in most browsers still. Couldn't we use a service worker to intercept all requests for JS files and just rewrite the bare imports there before returning the modified response to the web application? Seems we could then have import maps everywhere service workers with the fetch listener are implemented. I'm sure using service workers to rewrite responses could be useful elsewhere as well

**Comment by guybedford** [comment]
Hi @lastmjs 

> It looks like the import maps polyfill doesn't work in most browsers still

I'd argue 86% very much fits the definition of most browsers.

> Couldn't we use a service worker to intercept all requests for JS files and just rewrite the bare imports there before returning the modified response to the web application?

Certainly. I'm usually weary of service workers for this kind of thing due to the setup / upgrade / first run kinds of issues, which I find defeat the purpose of the unbuilt workflow for me.

See also https://github.com/Rich-Harris/shimport which could possibly be extended to support import maps too.

Personally I see SystemJS as the compatibility path and this project as the new path. The reason being that we don't want to sacrifice performance and the great thing about this approach is being able to use Web Assembly since the compatibility exactly matches. But carve out your own workflows for sure!

Always happy to discuss.
