### ISSUE TITLE
Error stack is missing

### ISSUE THREAD

**Issue by GongT** [guybedford/es-module-shims#75]
```javascript
const startAt = new Date();importShim(CURRENT_APP_URL, undefined).then(complete, criticalError);
```

![image](https://user-images.githubusercontent.com/2265048/69421027-ecd7ba00-0d5a-11ea-8df7-68b5b845a4ee.png)

The "stack" does not contains any stack info, can not know where the error comes from.

There are no cross origin issue.

**Comment by guybedford** [comment]
Can you share the code that is causing this? A minimal replication would help a lot as this sounds like it would be a bug in es module lexer (https://github.com/guybedford/es-module-lexer).

**Comment by trusktr** [comment]
I'm trying to use this, and it works great because it makes import maps work consistently in all browser, but when there's an error in my code, I see a stack trace unrelated to my code, pointing inside of es-module-shims. For example:

<img width="481" alt="Screen Shot 2019-11-30 at 3 18 01 PM" src="https://user-images.githubusercontent.com/297678/69907147-a13d9580-1384-11ea-8d3c-6e96682da853.png">

If I remove the shims, and run my code in Chrome, then I can see the stack trace relative to my code. I might just have to disable es-module-shims temporarily while debugging, then restore it so everything works in all browsers once deployed.

**Comment by trusktr** [comment]
Hmmm, well, the stack trace looks fine in Chrome with es-module-shims enabled:

<img width="506" alt="Screen Shot 2019-11-30 at 3 19 46 PM" src="https://user-images.githubusercontent.com/297678/69907167-f8dc0100-1384-11ea-8b86-7571de12799a.png">


In Firefox, I don't even see any stack trace for this error.

**Comment by GongT** [comment]
The original error has already fixed, And I do know the exact reason. But I found some other errors without stack:

### A
```javascript
// imported.js
export const A = 1;

// main.js
import {notExported} from "./imported.js"
console.log(notExported);
```
This will cause:
> VM42350:37 SyntaxError: The requested module 'blob:http://gongt-linux:15001/dd8dcacd-23d2-493e-b274-fdfb8c669864' does not provide an export named 'notExported'

I can find original file by searching the generated id from "Network" tab. But still no info about "where" the import statement is.
Or I can search notExported globally.

### B
```javascript
// imported.js
"left hand" = "assign"        // SyntaxError: Invalid left-hand side in assignment
if(a==1||b=2);                // SyntaxError: Unexpected token '='
```
These kind of error do not include any info about where it comes from. Global error handler "suddenly" receive such an error.

(of course I won't write anything like this normally, just a test)

### ps
A suggestion: maybe it should include some human readable string in generated module name.
eg: `blob:http://gongt-linux:15001/dd8dcacd-23d2-493e-b274-fdfb8c669864?original_path=/some/test.js`
