### ISSUE TITLE
evaluating modules with blob object URLs vs inline script

### ISSUE THREAD

**Issue by khangsfdc** [guybedford/es-module-shims#83]
Hi,

I have a similar use case, so wondering if there is a rationale (e.g. performance) for using `script.src = URL.createObjectURL(blob)` to evaluate modules instead of just creating an inline script?

**Comment by guybedford** [comment]
@khangsfdc this is necessary because if the specifiers are left alone then we cannot refer to the transformed sources. And if any specifier is rewritten then we have a transformed source!

Blob URLs don't come with any significant performance cost.

Note this project can also be used to implement arbitrary transforms with the fetch hook.

**Comment by khangsfdc** [comment]
@guybedford makes, sense, thank you!
