### ISSUE TITLE
DOMContentLoaded not fired in <script type="module-shim">

### ISSUE THREAD

**Issue by bendavis78** [guybedford/es-module-shims#99]
I've noticed that if I add a `DOMContentLoaded` event listener inside a <script type="module-shim">, it doesn't get fired. Is the module shim loaded after DOMContentLoaded? If so, is this the expected behavior?

**Comment by guybedford** [comment]
In general we attempt to match native modules. Native modules implement defer semantics so I suspect they likely behave the same.

Perhaps try a test with a native module doing the same and see if it fires? If there are any differences I'm open to any changes we can make to do that, it's great to be verifying these cases.

**Comment by bendavis78** [comment]
Here's a quick test I did:

```html
<!DOCTYPE html>
<html>
  <body>
    <h1>This is a test</h1>
    <script type="module">
      document.addEventListener('DOMContentLoaded', () => {
        console.log('DOMContentLoaded => fired from module');
      });
    </script>
    <script>
      document.addEventListener('DOMContentLoaded', () => {
        console.log('DOMContentLoaded => fired from normal script');
      });
    </script>
  </body>
</html>
```

When testing with native, both events are fired, however the event from the module fires 2nd.

When I add `es-module-shims.js` in `<head>` and set the module tag to `type="module-shim"`, the event from the module is never fired.

According to [this](https://javascript.info/script-async-defer):
> Scripts with defer always execute when the DOM is ready (but before DOMContentLoaded event).

**Comment by guybedford** [comment]
Thanks for investigating this further @bendavis78, very interesting to see. If it were possible to implement an artificial delay into DOMContentLoaded I'd be all for an approach here - I'm just not sure if that is possible to do actually?

**Comment by dbackeus** [comment]
If this can't be fixed it would seem appropriate to at least document this discrepancy in the README. I just spent significant time trying to comprehend why my modules behaved as `async` instead of the expected `defer`(looked at https://gist.github.com/jakub-g/385ee6b41085303a53ad92c7c8afd7a6 as a reference for expected behaviour).

**Comment by chase-moskal** [comment]
hello, i was interested in this issue, and so i made a [codepen that seems to show DOMContentLoaded is actually working](https://codepen.io/ChaseMoskal/pen/qBmmvVB?editors=1002)
```html
<script type=module-shim>
  document.addEventListener("DOMContentLoaded", () =>
    console.log(Date.now(), "dom content loaded works"))
</script>
<script src="https://unpkg.com/es-module-shims@0.12.1/dist/es-module-shims.js"></script>
```
i think the key was just to remove `async` and `defer` from all the script tags?

**Comment by guybedford** [comment]
Interesting to hear, strictly speaking DOMContentLoaded attachment should be using the pattern:

```js
if (document.readyState === 'loading') {  // Loading hasn't finished yet
  document.addEventListener('DOMContentLoaded', doSomething);
} else {  // `DOMContentLoaded` has already fired
  doSomething();
}
```

**Comment by dbackeus** [comment]
@chase-moskal that's probably due to codepen taking long enough to load whatever it's loading so that DOMContentLoaded hasn't already fired once es-module-shim is executed. It's important to keep in mind this issue is subject to race conditions.

Try adding the following to a local .html file and run it in Chrome and you should only get the hello from type="module":
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>es-module-shims DOMContentLoaded test</title>
		<script async src="https://cdn.jsdelivr.net/npm/es-module-shims@0.12.1/dist/es-module-shims.min.js"></script>
	</head>
	<body>
		<script type="module">
			document.addEventListener("DOMContentLoaded", () =>
    		console.log('Hello from type="module"'))
		</script>
		<script type="module-shim">
			document.addEventListener("DOMContentLoaded", () =>
    		console.log('Hello from type="module-shim"'))
		</script>
	</body>
</html>
```

**Comment by chase-moskal** [comment]
@dbackeus — ahah, an excellent point good sir — that's surely what's going on — i'll take your word for it that the issue would reproduce locally

**Comment by guybedford** [comment]
Load event re-firing has been implemented in https://github.com/guybedford/es-module-shims/pull/162 coming in the next release.

If this turns out to cause more issues do please post back here. There is an option to turn it off as well - https://github.com/guybedford/es-module-shims#no-load-event-retriggers.
